package uk.ac.imperial.evpool

import java.util.List
import java.util.ArrayList

import uk.ac.imperial.evpool.allocators.NeedBasedAllocator
import uk.ac.imperial.evpool.ProvisionPool
import uk.ac.imperial.evpool.actions.*
import uk.ac.imperial.evpool.facts.*
import uk.ac.imperial.evpool.RoundType

global org.apache.log4j.Logger logger
global org.drools.runtime.StatefulKnowledgeSession session

rule "Need based resource allocation"
	no-loop
	when
		$r : Round( type == RoundType.DEMAND, $t : number )
		$c : Cluster( allocationMethod == Allocation.NEED_BASED )
		$pool : ProvisionPool( cluster == $c )
		$poolMembers : List(size > 0) from accumulate( MemberOf( cluster == $c, $p : player ), collectList( $p ) )
	then
		logger.info("Need based order for resources in" + $c + " allocation pool:" + $pool.getQuantity());
        if (storage != null) {
            storage.getSimulation().getEnvironment().setProperty("c"+ $c.getId() +"-allocPool",
                    $r.getNumber(),
                    Double.toString($pool.getQuantity())
                    );
            storage.getSimulation().getEnvironment().setProperty("c"+ $c.getId() +"-agentCount",
                                $r.getNumber(),
                                Double.toString($poolMembers.size())
                                );
        }
		NeedBasedAllocator.allocate(session, $poolMembers, $pool.getQuantity(), $t );
		modify( $pool ) {
			setQuantity(0);
		}
end
